### PR TITLE
"hello"

### PR DESCRIPTION
**Pull request by rats-god**

### CODE REVIEW

**Comment by kelas** [comment]
Nicely done!


Do you feel like contributing a chapter on solving some other classic Euler
problem, e.g. p13?

**Comment by rats-god** [comment]
sure, might take me a moment to figure out a nice way to do it, but i'll take a stab at it and get back to you :)

**Comment by rats-god** [comment]
side note, because i don't know how else to send a message: 

"Rank zero, or niladic functions do not exist in k."

per a discussion in the k tree (https://chat.stackexchange.com/transcript/message/50491742#50491742) it looks like something like `{[]1+2}` might create a (useless?) niladic function?

**Comment by kelas** [comment]
right, `0 does exist, and it is mentioned at the bottom of the document,
and they are of some use.

kcc follows kiss principle

**Pull request closed without merging**
